version: '3.9'
services:
  database:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
#      - ./database/data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/html/
      - ./conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      - PHP_IDE_CONFIG=serverName=dev
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - database

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
        PMA_HOST: database
        PMA_USER: root
        PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - database
