SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS real_estate.cities;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE IF NOT EXISTS real_estate.cities (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
);
